# fly.toml app configuration file generated for prem-registry on 2023-05-11T11:34:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prem-registry"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
